sudo: required
language: node_js
node_js:
  - "8.1.3"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - "./install.sh"
  - "./build.sh"

# deploy:
  # provider: firebase
after_success:
   - firebase deploy --token $FIREBASE_TOKEN
