prose:
  rooturl: 'hugo_site'
  media: 'media'
  metadata:
    hugo_site/content:
      - name: "date"
        field:
          element: "text"
          value: "2018-02-10T21:30:10+10:30"
      - name: "title"
        field:
          element: "text"
          value: "My New Post"
