prose:
  rooturl: 'hugo_site'
  media: 'media'
  metadata:
    hugo_site/content:
      - name: "date"
        field:
          element: "text"
          value: CURRENT_DATETIME
      - name: "title"
        field:
          element: "text"
          value: "My New Post"
